### ISSUE TITLE
 How to create a multi module project with jpro ?

### ISSUE THREAD

**Issue by ghost** [JPro-one/HelloJPro-Maven#10]
I want to create a multi module maven javafx project with jpro like this project structure.

http://www.mkyong.com/wp-content/uploads/2018/10/maven-multi-module-0.png

How to create a project like this with JPro?

**Comment by FlorianKirmaier** [comment]
This question isn't really related to JPro.
Just look up the Maven documentation on how to do it - or check the blog of the screenshot.
Usually for one of the projects you want to use JPro. Just apply JPro to only this project.
