### ISSUE TITLE
Error while starting application.

### ISSUE THREAD

**Issue by ashokkumarvel** [JPro-one/HelloJPro-Maven#11]
my project contains web view.

**Comment by parasuraam** [comment]
`package com.jpro.hellojpro;
public @interface WebkitCall {
   String from() default "";
  }
`
How can I add this?

**Comment by FlorianKirmaier** [comment]
Webview is not supported, im sorry. You can embed HTML element with [HTMLView](https://www.jpro.one/api/2019.2.5/com/jpro/webapi/HTMLView.html) (with is the JPro equivalent)
