### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jfxwebkit

### ISSUE THREAD

**Issue by ghost** [JPro-one/HelloJPro-Maven#12]
There was no webview in my project.

Error : 

`[error] c.j.i.c.InstanceImpl - Error while starting application: java.lang.UnsatisfiedLinkError: no jfxwebkit in java.library.path: [C:\Program Files\Java\jdk-12\bin, C:\Windows\Sun\Java\bin, C:\Windows\system32, C:\Windows, C:\Program Files (x86)\Common Files\Oracle\Java\javapath, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, D:\install\sdk\android-ndk-r21\, D:\install\Git\cmd, D:\install\sdk\ndk\21.0.6113669\build, D:\install\cmake\bin, D:\install\nodejs\, C:\Program Files\Java\jdk-12\bin, C:\Users\prade\AppData\Local\Microsoft\WindowsApps, C:\Users\prade\AppData\Local\GitHubDesktop\bin, C:\Users\prade\AppData\Roaming\npm, .] at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660) at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827) at java.base/java.lang.System.loadLibrary(System.java:1902) at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:150) at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52) at com.sun.webkit.WebPage.lambda$static$0(WebPage.java:133) at java.base/java.security.AccessController.doPrivileged(AccessController.java:310) at com.sun.webkit.WebPage.<clinit>(WebPage.java:132) at javafx.scene.web.WebEngine.<init>(WebEngine.java:841) at javafx.scene.web.WebEngine.<init>(WebEngine.java:826) [warn] c.j.i.c.InstanceImpl - Application didn't show the stage. JPro is now calling show() [info] c.j.m.s.Util$ - WORKAROUND! setting XY for Window because current XY is NaN`

How can I solve this?

**Comment by FlorianKirmaier** [comment]
Hm, that shouldn't happen.
If we can reproduce it, then we can fix it.
I would need more information:
 * Java Version?
 * Maven Version? (Maybe try the maven-wrapper from the latest commit)
 * Is the project unchanged?
 * Which Windows version are you using?
 * Does it also happen in the HelloJPro project, which uses Gradle?

Please also try to find matching titles for your issues.

**Comment by poorvajappja** [comment]
My project 

[HelloJPro-Maven-master.zip](https://github.com/JPro-one/HelloJPro-Maven/files/4912611/HelloJPro-Maven-master.zip)

**Comment by FlorianKirmaier** [comment]
TerminalFX is using WebView.
When i start it using javafx11, i get the following error:
```
[error] c.j.i.c.InstanceImpl - Error while starting application: 
java.lang.NoClassDefFoundError: Could not initialize class com.sun.webkit.WebPage
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:841)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:826)
	at javafx.scene.web.WebView.<init>(WebView.java:260)
	at com.kodedu.terminalfx.TerminalView.<init>(TerminalView.java:33)
	at com.kodedu.terminalfx.Terminal.<init>(Terminal.java:33)
	at com.kodedu.terminalfx.TerminalTab.<init>(TerminalTab.java:28)
	at com.kodedu.terminalfx.TerminalBuilder.newTerminal(TerminalBuilder.java:57)
	at jtabbedterminal.jTabbedTerminal.addTerminalTab(jTabbedTerminal.java:231)
	at jtabbedterminal.jTabbedTerminal.start(jTabbedTerminal.java:219)
	at com.jpro.internal.config.ApplicationStarter$.$anonfun$startJApplication$1(ApplicationStarter.scala:133)
```

**Comment by poorvajappja** [comment]
TerminalFX  Version 1.0.8 works in JPro.
But , error when I enter text in text field.

Error at these two lines.

https://github.com/pgfearo/TerminalFX/blob/master/src/main/java/com/kodcu/TerminalTab.java#L137

https://github.com/pgfearo/TerminalFX/blob/master/src/main/java/com/kodcu/TerminalTab.java#L119

TerminalFX Version 1.0.8 works in JPro. The textfield also works in JPro. But not  at all the time.

**Comment by poorvajappja** [comment]
The error at text field. 
Why this error comes?
