### ISSUE TITLE
Could not find goal 'unpack-dependencies'

### ISSUE THREAD

**Issue by abiange** [JPro-one/HelloJPro-Maven#13]
When I release JPro it comes like this.

Error :

    [INFO] Scanning for projects...
    [WARNING] 
    [WARNING] Some problems were encountered while building the effective model for 
    com.sandec.jpro:hellojpro-maven:jar:1.0-SNAPSHOT
    [WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of 
    plugin org.apache.maven.plugins:maven-compiler-plugin @ line 96, column 21
    [WARNING] 
    [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
    [WARNING] 
    [WARNING] For this reason, future Maven versions might no longer support building such malformed 
    projects.
    [WARNING] 
    [INFO] 
    [INFO] ------------------< com.sandec.jpro:hellojpro-maven >-------------------
    [INFO] Building Hello JPro! 1.0-SNAPSHOT
    [INFO] --------------------------------[ jar ]---------------------------------
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  1.630 s
    [INFO] Finished at: 2020-07-13T14:00:39+05:30
    [INFO] ------------------------------------------------------------------------
    [ERROR] Could not find goal 'unpack-dependencies' in plugin org.apache.maven.plugins:maven-compiler- 
     plugin:3.1 among available goals testCompile, compile, help -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException

**Comment by FlorianKirmaier** [comment]
Thank you for reporting, but obviously we can not help you without further information.
A descriptive title would also help a bit.
We've changed the project to use the maven-wrapper, to avoid issues with old maven versions.

If the issue persists, I would need way more information. 
Is the project unchanged? 
Which Java version are you using? 
Which OS are you using?
Which exact command are you executing?

**Comment by abiange** [comment]
I am using java Version 8 and windows 10 os.

Command:  `mvn jpro:release`

**Comment by FlorianKirmaier** [comment]
Which maven version are you using?

**Comment by PradeepSimba** [comment]
`
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

</project>`

**Comment by poorvajappja** [comment]
`
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

</project>`

**Comment by abiange** [comment]
`
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

</project>`

**Comment by FlorianKirmaier** [comment]
@abiange 
Can you tell us how you solved your problem? This might help us to improve our documentation and/or our samples.
