### ISSUE TITLE
Compile and release does not work together

### ISSUE THREAD

**Issue by ryppo** [JPro-one/HelloJPro-Maven#4]
`mvn compile jpro:release`
runs into this exception:
`Failed to execute goal com.sandec.jpro:jpro-maven-plugin:2018.1.8:release (default-cli) on project <my-project>: Execution default-cli of goal com.sandec.jpro:jpro-maven-plugin:2018.1.8:release failed: java.io.FileNotFoundException: <my-project-path>\target\classes (Zugriff verweigert)`
Configuration: Win10, Maven 3.6.0, JDK8
**Solution**:
First compile, then release using
`mvn install jpro:release`
This issue is just for documentation. I guess that other developers can run into the same trap. Intuitively I chose `compile` because this is the documented way for `jpro:run`.
Anyway, thank you for the maven extension.

**Comment by FlorianKirmaier** [comment]
fixed in 2018.1.9
