### ISSUE TITLE
Deployment of config file

### ISSUE THREAD

**Issue by ryppo** [JPro-one/HelloJPro-Maven#6]
My question refers `jpro:release`.
Is it possible to deploy a file to the application root folder?
The use case: My application provides a config file in the application root folder. With maven plugins it is possible to copy it to the target folder (`${project.build.directory}`). But this file is not taken by `jpro:release`.
As an option copying the file to the classes folder (`${project.build.outputDirectory}`) helps a little bit. It is integrated in the application's jar file.
Obviously, it is not comfortable for the administrator, to dive into the application folder structure and edit a file in a defined jar.
It would be great, if there is an option (or common behavior), to copy target-folder root files.

**Comment by FlorianKirmaier** [comment]
@ryppo 
Thank you for your suggestion/feature request.

Do you have any existing maven-plugin in mind, which provides something similar which could be used as a blueprint for this feature?

One solution might look like the following:
```
<configurations>
  <jproReleaseFiles>
    <file>
      <source>${project.build.outputDirectory}/jproreleasefiles/config
      <outputDirectory>config</outputDirectory>
    </file>
  </jproReleaseFiles>
</configurations>
```
In this case, the mentioned file/folder config would be added to the release-zip.
What do you think about it?

**Comment by ryppo** [comment]
@FlorianKirmaier 
Great approach. You solution will solve my request. Adding the file(s)/folder to the release-zip keeps a consistant deployment-package, as expected.

Actually I use `maven-resources-plugin`. Configuration looks like this:

```
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-resources-plugin</artifactId>
   <version>3.0.2</version>
   <executions>
      <execution>
         <id>copy-root-files</id>
         <phase>package</phase>
         <goals>
            <goal>copy-resources</goal>
         </goals>
         <configuration>
            <outputDirectory>${project.build.outputDirectory}/</outputDirectory>
            <resources>
               <resource>
                  <directory>${basedir}</directory>
                  <includes>
                     <include>${application.config.file}</include>
                  </includes>
               </resource>
            </resources>
         </configuration>
      </execution>
   </executions>
</plugin>
```

**Comment by FlorianKirmaier** [comment]
Hi @ryppo 

We've added this feature to JPro, in the latest release 2018.1.10!

Here is a link to the documentation, which shows you how to use it:
[https://www.jpro.one/?page=docs/current/2.2/CONFIGURING_JPRO](https://www.jpro.one/?page=docs/current/2.2/CONFIGURING_JPRO)
