### ISSUE TITLE
When I download and import this project it not done.

### ISSUE THREAD

**Issue by ghost** [JPro-one/HelloJPro-Maven#8]
I import this project in intellij . But , the error comes module not found.
then I goes to jpro gradle project . But , I import the gradle project then it comes update the gradle.

there are lot of issues with this when I import this project.

Give a solution for this?

update the project .

**Comment by FlorianKirmaier** [comment]
Maybe you were using Java8? I would need more information to be able to help you.

**Comment by ghost** [comment]
It come module not found.

**Comment by FlorianKirmaier** [comment]
Thank you for the bug report! I was now able to reproduce and fix the problem.
